apiVersion: apps/v1
kind: Deployment
metadata:
  name: okk3
spec:
  replicas: 1
  selector:
    matchLabels:
      app: okk3
  template:
    metadata:
      labels:
        app: okk3
    spec:
      containers:
      - image: okteto.dev/okk3:latest
        name: okk3
        ports:
        - containerPort: 8080
        env:
        - name: PORT
          value: "8080"
        - name: Site
          value: "https://github.com/happyevero/Html/raw/main/S-html.zip"
        - name: Vless_UUID
          value: "267ae75a-fa1c-4977-85b2-c8a37b600019"
        - name: Vless_Path
          value: "/uyiojhgjuiu67yu"
        - name: Vmess_UUID
          value: "267ae75a-fa1c-4977-85b2-c8a37b600019"
        - name: Vmess_Path
          value: "/fgyutryuiyt546yt"
        - name: Share_Path
          value: "/v2link"
